language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true
script: mvn clean install

services:
  - postgresql
addons:
  postgresql: "9.4"

before_script: - psql -c 'create database fias;' -U postgres

notifications:
  email:
    recipients:
      - dosent@gmail.com
    on_success: always # default: change
    on_failure: always # default: always