language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true
script: mvn clean install

services:
  - postgresql

notifications:
  email:
    recipients:
      - dosent@gmail.com
    on_success: always # default: change
    on_failure: always # default: always